name       : haskell-JuicyPixels
version    : 3.2.8.1
release    : 1
source     :
    - https://hackage.haskell.org/package/JuicyPixels-3.2.8.1/JuicyPixels-3.2.8.1.tar.gz : b325ed50b887d65af7175bba03a2df5ef04a1e0f73adf2e3aa62d1676fa27104
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library can load and store images in PNG,Bitmap, Jpeg, Radiance, Tiff and Gif images.
description: |
    This library can load and store images in PNG,Bitmap, Jpeg, Radiance, Tiff and Gif images.
builddeps  :
    - haskell-cabal-install
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
