name       : haskell-JuicyPixels
version    : 3.2.9.5
release    : 2
source     :
    - https://hackage.haskell.org/package/JuicyPixels-3.2.9.5/JuicyPixels-3.2.9.5.tar.gz : 849c6cf4a613f906f7e553a1baefe9c0dc61c13b41a5f5b9605cf80e328cc355
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library can load and store images in PNG,Bitmap, Jpeg, Radiance, Tiff and Gif images.
description: |
    This library can load and store images in PNG,Bitmap, Jpeg, Radiance, Tiff and Gif images.
builddeps  :
    - haskell-cabal-install
    - haskell-mtl
    - haskell-vector
    - haskell-zlib
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
